openapi: 3.0.0
info:
  title: CovidNYTimes API Docs
  version: '1.0'
  description: "API documentation for COVID-19 2020 cumulative counts of infection in the United States. Provided by the New York Times, based on data collected from state and local agencies.\n\nThe data begins with the first reported coronavirus case in Washington State on Jan. 21, 2020.\n\nCount of patients occurs at the place where they are treated, not where they live.\n\n**Confirmed**\nThis data reflects *Confirmed* cases. Cases are confirmed when they are reported by federal, state, territorial or local government agency. \n\n**Dates**\nEach date includes the cumulative count of cases or deaths reported on that day. \n"
  contact:
    email: covid-data@nytimes.com
    name: New York Times
    url: 'https://github.com/nytimes/covid-19-data'
  license:
    url: 'https://github.com/nytimes/covid-19-data/blob/master/LICENSE'
    name: License (CC BY-NC)
servers:
  - url: 'https://covapi.herokuapp.com'
    description: restapi
paths:
  /api/timeline/states:
    get:
      summary: GET states
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineState'
              examples:
                Timeline Example By State:
                  value:
                    Alabama:
                      '2020-04-13':
                        cases: '3805'
                        deaths: '104'
                      '2020-04-14':
                        cases: '3953'
                        deaths: '114'
                      '2020-04-15':
                        cases: '4241'
                        deaths: '123'
                      '2020-04-16':
                        cases: '4404'
                        deaths: '137'
                    California:
                      '2020-04-13':
                        cases: '275'
                        deaths: '1'
                      '2020-04-14':
                        cases: '282'
                        deaths: '1'
                      '2020-04-15':
                        cases: '288'
                        deaths: '2'
                      '2020-04-16':
                        cases: '296'
                        deaths: '2'
            application/xml:
              schema:
                type: object
                properties: {}
              examples:
                example-1: {}
      operationId: get-api-timeline-states
      description: "Returns a collection of states with cumulative infection counts of COVID-19 in the United States, listed as a timeline. Dates in the timeline for a State start with the first incident being reported to a government authority.\n\nList of states, with postal codes and FIPS codes is at \n\nhttps://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs143_013696"
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
      tags:
        - Timeline Endpoints by State
      requestBody:
        description: 'https://covapi.herokuapp.com/api/timeline/states'
    parameters: []
  '/api/timeline/states/{state}':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET state
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineDate'
              examples:
                Timeline Example for California:
                  value:
                    '2020-04-01':
                      cases: '9816'
                      deaths: '212'
                    '2020-04-02':
                      cases: '11190'
                      deaths: '247'
                    '2020-04-03':
                      cases: '12569'
                      deaths: '282'
                    '2020-04-04':
                      cases: '13796'
                      deaths: '323'
                    '2020-04-05':
                      cases: '15076'
                      deaths: '349'
                    '2020-04-06':
                      cases: '16284'
                      deaths: '386'
                    '2020-04-07':
                      cases: '17540'
                      deaths: '447'
                    '2020-04-08':
                      cases: '19043'
                      deaths: '506'
                    '2020-04-09':
                      cases: '20191'
                      deaths: '548'
                    '2020-04-10':
                      cases: '21366'
                      deaths: '594'
                    '2020-04-11':
                      cases: '22421'
                      deaths: '632'
                    '2020-04-12':
                      cases: '23323'
                      deaths: '676'
                    '2020-04-13':
                      cases: '24334'
                      deaths: '725'
                    '2020-04-14':
                      cases: '25758'
                      deaths: '778'
                    '2020-04-15':
                      cases: '27107'
                      deaths: '885'
                    '2020-04-16':
                      cases: '28142'
                      deaths: '971'
                    '2020-04-17':
                      cases: '29398'
                      deaths: '1050'
            application/xml:
              schema:
                type: object
                properties: {}
              examples:
                example-1: {}
      operationId: get-api-timeline-states-state
      description: "Returns the timeline information with cumulative infection counts of COVID-19 in the United States, for a single state. \n\nThe state is specified as a Path Param."
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
      tags:
        - Timeline Endpoints by State
  '/api/timeline/states/{state}/counties':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET counties per state
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Timeline Example By Counties:
                  value:
                    San Diego:
                      '2020-04-10':
                        cases: '107'
                        deaths: '1'
                      '2020-04-11':
                        cases: '110'
                        deaths: '1'
                      '2020-04-12':
                        cases: '114'
                        deaths: '1'
                      '2020-04-13':
                        cases: '117'
                        deaths: '1'
                      '2020-04-14':
                        cases: '120'
                        deaths: '1'
                      '2020-04-15':
                        cases: '124'
                        deaths: '1'
                      '2020-04-16':
                        cases: '125'
                        deaths: '1'
                      '2020-04-17':
                        cases: '127'
                        deaths: '1'
                    San Mateo:
                      '2020-04-10':
                        cases: '638'
                        deaths: '21'
                      '2020-04-11':
                        cases: '652'
                        deaths: '21'
                      '2020-04-12':
                        cases: '652'
                        deaths: '21'
                      '2020-04-13':
                        cases: '701'
                        deaths: '21'
                      '2020-04-14':
                        cases: '747'
                        deaths: '21'
                      '2020-04-15':
                        cases: '767'
                        deaths: '28'
                      '2020-04-16':
                        cases: '767'
                        deaths: '28'
                      '2020-04-17':
                        cases: '797'
                        deaths: '28'
      operationId: get-api-timeline-states-state-counties
      description: List of counties for the state selected
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
      tags:
        - Timeline Endpoints by State
  '/api/timeline/states/{state}/counties/{county}':
    parameters:
      - $ref: '#/components/parameters/county'
      - $ref: '#/components/parameters/state'
    get:
      summary: GET county per state
      tags:
        - Timeline Endpoints by County
      responses: {}
      operationId: get-api-timeline-states-state-counties-county
      description: County per state
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  /api/timeline/counties:
    get:
      summary: GET counties
      tags:
        - Timeline Endpoints by County
      responses: {}
      operationId: get-api-timeline-counties
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/timeline/counties/{state}':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET counties per state
      tags:
        - Timeline Endpoints by County
      responses: {}
      operationId: get-api-timeline-counties-state
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/timeline/counties/{state}/{county}':
    parameters:
      - $ref: '#/components/parameters/state'
      - $ref: '#/components/parameters/county'
    get:
      summary: GET county per state
      tags:
        - Timeline Endpoints by County
      responses: {}
      operationId: get-api-timeline-counties-state-county
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  /api/total/states:
    get:
      summary: GET states
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
      operationId: get-api-total-states
      tags:
        - Totals Endpoints by State
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/total/states/{state}':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET state
      tags:
        - Totals Endpoints by State
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cases:
                    type: string
                    description: Cumulative Total of infections for the State
                  deaths:
                    type: string
                    description: Cumulative Total of deaths for the State
              examples:
                Example Response for California:
                  value:
                    cases: '29398'
                    deaths: '1050'
      operationId: get-api-total-states-state
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
      description: 'https://covapi.herokuapp.com//api/total/states/California'
  '/api/total/states/{state}/counties':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET counties per state
      tags:
        - Totals Endpoints by State
      responses: {}
      operationId: get-api-total-states-state-counties
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/total/states/{state}/counties/{county}':
    parameters:
      - $ref: '#/components/parameters/state'
      - $ref: '#/components/parameters/county'
    get:
      summary: GET county per state
      tags:
        - Totals Endpoints by State
      responses: {}
      operationId: get-api-total-states-state-counties-county
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  /api/total/counties:
    get:
      summary: GET counties
      responses: {}
      operationId: get-api-total-counties
      tags:
        - Totals Endpoints by County
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/total/counties/{state}':
    parameters:
      - $ref: '#/components/parameters/state'
    get:
      summary: GET state per county
      tags:
        - Totals Endpoints by County
      responses: {}
      operationId: get-api-total-counties-state
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
  '/api/total/counties/{state}/{county}':
    parameters:
      - $ref: '#/components/parameters/state'
      - $ref: '#/components/parameters/county'
    get:
      summary: GET county per state
      tags:
        - Totals Endpoints by County
      responses: {}
      operationId: get-api-total-counties-state-county
      parameters:
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/fipsKey'
      description: ''
components:
  schemas:
    TimelineState:
      x-examples:
        State example:
          Alabama:
            '2020-04-13':
              cases: '3805'
              deaths: '104'
            '2020-04-14':
              cases: '3953'
              deaths: '114'
            '2020-04-15':
              cases: '4241'
              deaths: '123'
            '2020-04-16':
              cases: '4404'
              deaths: '137'
          California:
            '2020-04-13':
              cases: '275'
              deaths: '1'
            '2020-04-14':
              cases: '282'
              deaths: '1'
            '2020-04-15':
              cases: '288'
              deaths: '2'
            '2020-04-16':
              cases: '296'
              deaths: '2'
      type: object
      description: |-
        Collection of States with a Timeline of infections.

        States can be listed by their complete name or FIPS codes.

        Timeline is broken out by Date with cumulative counts of infections and deaths. The List of Dates for a State starts from the first incidence of infection reported to a government authority.

        The Date object can contain cases, deaths or both depending on the `mode` query parameter.
      title: Timeline State
      x-tags:
        - Response Objects
      properties:
        Date:
          type: object
          description: |-
            Date an infection is registered in the State. Format is YYYY-MM-DD.

            The List of Dates for a State starts from the first incidence of an infection being reported to a government authority.
          example: '2020-04-01'
          properties:
            cases:
              type: string
              description: Cumulative count of infections per Date.
              example: '10'
            deaths:
              type: string
              description: Cumulative count of deaths per Date.
              example: '1'
    TimelineDate:
      type: object
      title: Timeline Date
      description: "Collection of Timeline of infections. This can be requested for a state or for a county within the state depending on the Path parameters. \n\nThe List of Dates for a State starts from the first incidence of an infection being reported to a government authority.\n\nThe Date object can contain cases, deaths or both depending on the `mode` query parameter.\n\nDate format is YYYY-MM-DD."
      example: '2020-04-01'
      properties:
        cases:
          type: string
          description: Cumulative count of infections per Date.
          example: '10'
        deaths:
          type: string
          description: Cumulative count of infections per Date.
          example: '1'
    TotalsState:
      type: object
      title: TotalsState
      description: |-
        Collection of States with cumulative counts of infections and deaths.

        States can be listed by their complete name or FIPS codes.

        The State object can contain cases, deaths or both depending on the `mode` query parameter.
      example: California
      properties:
        cases:
          type: string
          description: Cumulative Total of infections per State
          example: '10'
        deaths:
          type: string
          description: Cumulative Total of deaths per State
          example: '1'
    TimelineCounty:
      title: TimelineCounty
      type: object
      x-examples:
        Timeline County Example for California:
          San Diego:
            '2020-04-10':
              cases: '107'
              deaths: '1'
            '2020-04-11':
              cases: '110'
              deaths: '1'
            '2020-04-12':
              cases: '114'
              deaths: '1'
            '2020-04-13':
              cases: '117'
              deaths: '1'
            '2020-04-14':
              cases: '120'
              deaths: '1'
            '2020-04-15':
              cases: '124'
              deaths: '1'
            '2020-04-16':
              cases: '125'
              deaths: '1'
            '2020-04-17':
              cases: '127'
              deaths: '1'
          San Mateo:
            '2020-04-10':
              cases: '638'
              deaths: '21'
            '2020-04-11':
              cases: '652'
              deaths: '21'
            '2020-04-12':
              cases: '652'
              deaths: '21'
            '2020-04-13':
              cases: '701'
              deaths: '21'
            '2020-04-14':
              cases: '747'
              deaths: '21'
            '2020-04-15':
              cases: '767'
              deaths: '28'
            '2020-04-16':
              cases: '767'
              deaths: '28'
            '2020-04-17':
              cases: '797'
              deaths: '28'
      properties:
        Date:
          type: object
          properties:
            cases:
              type: string
            deaths:
              type: string
      description: ''
  parameters:
    mode:
      name: mode
      in: query
      description: |-
        Indicates if the counts of cases or the counts of deaths are desired.

        Can have 2 values `cases`, `deaths`. Default both are returned
      schema:
        type: string
      enum:
        - cases
        - deaths
    fipsKey:
      name: fipsKey
      in: query
      description: 'FIPS Key = true, returns the state and county keys as FIPS code values.'
      schema:
        type: string
      enum:
        - true
        - false
    state:
      name: state
      in: path
      description: "Name of the State. \\n\\nState name can be the full name of the state, postal code, or the FIPS code."
      schema:
        type: string
      required: true
    county:
      name: county
      in: path
      description: "Name of the County. \\n\\nCounty name can be the full name of the county, or the FIPS code."
      schema:
        type: string
      required: true
